name: diecasting
channels:
  - defaults
dependencies:
  - anyio=4.7.0=py311haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py311h02ab6af_0
  - asttokens=3.0.0=py311haa95532_0
  - async-lru=2.0.4=py311haa95532_0
  - attrs=24.3.0=py311haa95532_0
  - babel=2.16.0=py311haa95532_0
  - beautifulsoup4=4.13.5=py311haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py311haa95532_0
  - blosc=1.21.6=h4190f5b_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.4.2=py311h57dcf0c_0
  - branca=0.8.1=py311haa95532_0
  - brotli-python=1.0.9=py311h5da7b33_9
  - brotlicffi=1.0.9.2=py311h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.8.3=py311haa95532_0
  - cffi=1.17.1=py311h827c3e9_1
  - cfitsio=3.470=h2bbff1b_7
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.1=py311haa95532_0
  - contourpy=1.3.1=py311h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.16=py311h885b0b7_0
  - decorator=5.2.1=py311haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - folium=0.14.0=py311haa95532_0
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.55.3=py311h827c3e9_0
  - freetype=2.13.3=h0620614_0
  - freexl=2.0.0=hd7a5696_0
  - geopandas=1.1.1=py311haa95532_0
  - geopandas-base=1.1.1=py311haa95532_0
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.7.0=h4545760_3
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=py311haa95532_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.12.1=h51c971a_3
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.30.1=py311haa95532_0
  - ipython=9.1.0=py311haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - ipywidgets=7.6.5=pyhd3eb1b0_2
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.2=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.9.25=py311haa95532_0
  - jsonschema=4.25.0=py311haa95532_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - jupyter=1.1.1=py311haa95532_0
  - jupyter-lsp=2.2.5=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_0
  - jupyter_console=6.6.3=py311haa95532_0
  - jupyter_core=5.8.1=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_0
  - jupyter_server=2.16.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - jupyterlab=4.4.7=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.27.3=py311haa95532_0
  - jupyterlab_widgets=3.0.15=py311haa95532_0
  - kealib=1.5.0=hde4a422_1
  - kiwisolver=1.4.8=py311h5da7b33_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libboost=1.82.0=h3399ecb_2
  - libcurl=8.15.0=h2300eb9_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libgdal=3.6.2=h0e70117_7
  - libglib=2.84.2=h405b238_0
  - libiconv=1.16=h2bbff1b_3
  - libkml=1.3.0=h63940dd_7
  - libkrb5=1.21.3=h885b0b7_4
  - libnetcdf=4.8.1=h6685c40_4
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libsodium=1.0.20=h83e8143_0
  - libspatialite=5.1.0=h25d3e1c_1
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzip=1.8.0=h289538f_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mapclassify=2.10.0=py311haa95532_0
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib=3.10.6=py311haa95532_0
  - matplotlib-base=3.10.6=py311h43afe63_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - minizip=4.0.3=hb68bac4_0
  - mistune=3.1.2=py311haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - narwhals=1.31.0=py311haa95532_1
  - nbclient=0.10.2=py311haa95532_0
  - nbconvert=7.16.6=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbconvert-pandoc=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - networkx=3.5=py311haa95532_0
  - notebook=7.4.5=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_0
  - numexpr=2.11.0=py311hdb065b2_0
  - numpy=1.26.4=py311hdab7c0b_0
  - numpy-base=1.26.4=py311hd01c5d8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.17=h35632f6_0
  - overrides=7.4.0=py311haa95532_0
  - packaging=25.0=py311haa95532_0
  - pandas=2.3.2=py311ha5e6156_0
  - pandoc=2.12=haa95532_3
  - pandocfilters=1.5.1=py311haa95532_0
  - parso=0.8.4=py311haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.1.0=py311h096bfcc_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.3.7=py311haa95532_0
  - plotly=6.3.0=py311hbc747e5_0
  - poppler=24.09.0=h6558a74_1
  - poppler-data=0.4.11=haa95532_1
  - proj=9.3.1=ha107b6e_0
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.43=py311haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=7.0.0=py311h02ab6af_0
  - pure_eval=0.2.3=py311haa95532_0
  - pycparser=2.23=py311haa95532_0
  - pydeck=0.9.1=py311haa95532_0
  - pygments=2.19.1=py311haa95532_0
  - pyogrio=0.10.0=py311he5c4563_0
  - pyparsing=3.2.0=py311haa95532_0
  - pyproj=3.6.1=py311h8a0a45e_1
  - pyqt=6.9.1=py311h12ec796_0
  - pyqt6-sip=13.10.2=py311h630b2a1_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.13=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.20.0=py311haa95532_0
  - python-json-logger=3.2.1=py311haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311h885b0b7_0
  - pywinpty=2.0.15=py311h72d21ff_0
  - pyyaml=6.0.2=py311h827c3e9_0
  - pyzmq=27.1.0=py311h7149c55_0
  - qhull=2020.2=h59b6b97_2
  - qtbase=6.9.2=hd965823_0
  - qtconsole=5.6.1=py311haa95532_1
  - qtdeclarative=6.9.2=h88b4c33_0
  - qtpy=2.4.3=py311haa95532_0
  - qtsvg=6.9.2=h30ace32_0
  - qttools=6.9.2=h7e7b719_0
  - qtwebchannel=6.9.2=heb02b0b_0
  - qtwebsockets=6.9.2=heb02b0b_0
  - referencing=0.30.2=py311haa95532_0
  - requests=2.32.5=py311haa95532_0
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.22.3=py311h636fa0f_0
  - scikit-learn=1.7.1=py311h3fbe716_0
  - scipy=1.16.0=py311h242c13b_0
  - seaborn=0.13.2=py311haa95532_3
  - send2trash=1.8.2=py311haa95532_1
  - setuptools=78.1.1=py311haa95532_0
  - shapely=2.0.5=py311h82fc408_0
  - sip=6.12.0=py311h706e071_0
  - six=1.17.0=py311haa95532_0
  - sniffio=1.3.0=py311haa95532_0
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.18.1=py311haa95532_0
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tiledb=2.3.3=hd8964de_3
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py311h827c3e9_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py311h827c3e9_1
  - uriparser=0.9.8=h1a0bd13_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py311haa95532_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.8.0=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - widgetsnbextension=3.5.2=py311haa95532_1
  - win_inet_pton=1.1.0=py311haa95532_0
  - winpty=0.4.3=4
  - xerces-c=3.2.4=hd77b12b_1
  - xyzservices=2022.9.0=py311haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\USER\.conda\envs\diecasting
